version: '1.0'

services:
  backend:
    image: 'final-project-iso'
    container_name: 'backend-container'
    depends_on:
      - db
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_USERNAME=dauren
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dauren
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
    ports:
      - 8000:8888

  db:
    image: 'postgres'
    container_name: 'pg-container'
    environment:
      - POSTGRES_USER=dauren
      - POSTGRES_PASSWORD=1234
    ports:
      - 2345:5432